### ISSUE TITLE
Associate duplicated events in MOP's DB and implement custom Target model

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#162]
Surveys with overlapping regions, such as OGLE and MOA, can independently detect the same event.  
Currently MOP handles these as distinct events and makes no attempt to cross-match them.  
This is going to prevent us upgrading to the current and future versions of the TOM Toolkit (v2.18.4 upwards) which include more sophisticated target-matching tools. 

This includes a number of tasks:
- [x] Update to TOM Toolkit v2.18.4 to access the new Target matching functions
- [x] Develop a new management command to review all existing Targets in the MOP DB
- [x] Determine how the command should merge the existing data products for duplicated events #134 
- [x] Update MOP's custom templates to display alias names where appropriate.

**Comment by rachel3834** [comment]
Since the target matching features of the TOM Toolkit have been released in the same version as custom Target models, it makes sense to make these changes during one migration. 

I've implemented a custom MicrolensingTarget model, together with management commands customized to migrate all MOP's extra parameters to model fields.  

I've also updated MOP's UI to use the new custom Target model, together with all of MOP's cronjob tasks, views and associated test code.

**Comment by rachel3834** [comment]
In the process of migrating the production database, it became clear that the 20 characters allowed for the observing_mode field is too short and should be changed to max_length=30.

**Comment by rachel3834** [comment]
Experience showed that it was easiest to convert to the new Target model and then do the merging of duplicate events.  
For the dev DB the duplicates have been removed, along with their extra params but the conversion of the extra_params should be re-run.

**Comment by rachel3834** [comment]
ASASN-21mc had lightcurve ReducedDatums with an unknown source specified; these need to be re-uploaded.

**Comment by rachel3834** [comment]
This seems to be a wide-spread problem and mostly seems to refer to data uploaded by the pipeline, which at some early stage presumably didn't specify the data source.  Wrote a separate command tool to review and update the affected data products before continuing with the duplicate event identification.

**Comment by rachel3834** [comment]
Attempting to run the management command to resolve the duplicates, the process (which was previously running fine) is now being Killed immediately on start up.  Log reports:

mop-6568bf569-tq6w7 nginx 10.100.24.119 - - [23/Jun/2024:00:20:28 +0000] "GET /targets/ HTTP/1.1" 200 4159661 "https://mop.lco.global/prioritytargets/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "184.189.222.100"
- mop-6568bf569-tq6w7 › nginx
- mop-6568bf569-cv7cf › mop
failed to tail: read tcp 192.168.1.16:60285->52.25.2.26:443: read: connection reset by peer, will retry
- mop-6568bf569-cv7cf › nginx
failed to tail: read tcp 192.168.1.16:60285->52.25.2.26:443: read: connection reset by peer, will retry
+ mop-6568bf569-cv7cf › mop
- mop-6568bf569-tq6w7 › mop
+ mop-6568bf569-tq6w7 › nginx
failed to tail: read tcp 192.168.1.16:60285->52.25.2.26:443: read: connection reset by peer, will retry
+ mop-6568bf569-tq6w7 › mop
failed to tail: read tcp 192.168.1.16:60285->52.25.2.26:443: read: connection reset by peer, will retry
+ mop-6568bf569-cv7cf › nginx

**Comment by rachel3834** [comment]
TNS class and TNS name are set by query at the time of target ingest but are set unreliably because TNS has a low max query limit.  These parameters are not merged during the deduplication process since they should be the same for all matching targets; however they may or may not have been set in the first place. 

Similarly, the Gaia catalog query is assumed to be the same for merged targets, but since this code was implemented fairly recently, not all targets have this information.  

For consistency, it would be best to have some way to re-run these functions for all targets systemtically.

**Comment by rachel3834** [comment]
Gaia20fsn/ZTF20aculhzd - example of ZTF with dataproducts with no source name which are therefore not merged properly?
Code adjusted to recognize a wider range of source_names such as ZTFDR3 as well as ZTF

**Comment by rachel3834** [comment]
Need to check data harvesters to make sure they harvest data for duplicate events properly

**Comment by rachel3834** [comment]
Target post save hook: MOA-2023-BLG-352 created: False
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InternalError_: invalid memory alloc request size 1073741824


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mop/./manage.py", line 21, in <module>
    main()
  File "/mop/./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/mop/mop/management/commands/associate_duplicate_events.py", line 95, in handle
    self.merge_extra_params(primary_target, matching_targets)
  File "/mop/mop/management/commands/associate_duplicate_events.py", line 166, in merge_extra_params
    primary_target.store_parameter_set(update_params)
  File "/mop/microlensing_targets/models.py", line 248, in store_parameter_set
    self.save()
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/tom_targets/base_models.py", line 422, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 990, in _save_table
    updated = self._do_update(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: invalid memory alloc request size 1073741824

**Comment by rachel3834** [comment]
Further investigation into the out of memory errors revealed that in a small number of cases (3 in >11,000) the fit_covariance parameter contained malformed data.  Specifically, these were found to have extremely long strings (over 200 million characters!) consisting almost entirely of backslashes (an exception character); these parameters alone require > 100MB, so naturally the process ran out of resources.  

This parameter is populated by the model fitting process, but such an output has never been seen to be produced in the normal operation of pyLIMA, so it is hard to understand where these excessive strings came from.  Alternatively something may have gone wrong during the conversion of this parameter, which was previously stored as a string extra_param of variable length to the new JSONField model attribute.  

To resolve this issue, I wrote a management command that review all of the entries for this parameter for all targets, including better exception handling, and ensured that all entries were properly converted to a JSON dictionary. 

- [ ] Update the run_TAP code that loads this parameter and the model method that outputs it to use the new format.

**Comment by rachel3834** [comment]
- [ ] Priority Targets page lists finished targets with NaN TAP priority
- [ ] harvest_ogle needs to be able to extract the OGLE name for an event, even if it is one of the aliases, in order to be able to retrieve the lightcurve data
- [ ] Switch on cronjobs

**Comment by rachel3834** [comment]
Excluding NaN values from Django queries turns out to be non-trival.  These values are stored as FloatFields and there doesn't seem to be any built-in support for excluding these during queries.  The nearest reference I can find in the Django forums indicated a previous issue to prevent NaNs being stored for DecimalFields but not FloatFields.  

The best approach seems to be to intercept NaNs in the code and reset these values to the default of zero. 

This requires that the priorities be re-calculated for all targets in the DB.  This doesn't normally happen, since run_TAP only operates on alive events outside the HCZ, so there are many events outside of this range that essentially have old values left over from the merge and migration.  So I've implemented a command to enable me to run this calculation for arbitrary selections of events.

**Comment by rachel3834** [comment]
The migration of the DB and the merging of duplicate targets is now complete; all code in MOP has been updated to use the new custom Targets.
