### ISSUE TITLE
Target groupings are broken

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#169]
Going to the target groupings menu option produces a 500 error and the following log output:

```
mop-6cdfd98d9-q8ntp mop 127.0.0.1 - - [01/Jul/2024:22:17:27 +0000] "POST /targetselection/ HTTP/1.1" 200 7086 "https://mop.lco.global/targetselection/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
mop-6cdfd98d9-q8ntp mop 127.0.0.1 - - [01/Jul/2024:22:18:52 +0000] "GET /targetselection/ HTTP/1.1" 200 6526 "https://mop.lco.global/targetselection/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
mop-6cdfd98d9-q8ntp mop Internal Server Error: /targets/targetgrouping/
mop-6cdfd98d9-q8ntp mop Traceback (most recent call last):
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
mop-6cdfd98d9-q8ntp mop     response = get_response(request)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 199, in _get_response
mop-6cdfd98d9-q8ntp mop     response = self.process_exception_by_middleware(e, request)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
mop-6cdfd98d9-q8ntp mop     response = middleware_method(request, exception)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/tom_common/middleware.py", line 29, in process_exception
mop-6cdfd98d9-q8ntp mop     raise exception
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
mop-6cdfd98d9-q8ntp mop     response = wrapped_callback(request, *callback_args, **callback_kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
mop-6cdfd98d9-q8ntp mop     return self.dispatch(request, *args, **kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
mop-6cdfd98d9-q8ntp mop     return handler(request, *args, **kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/views/generic/list.py", line 154, in get
mop-6cdfd98d9-q8ntp mop     self.object_list = self.get_queryset()
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/guardian/mixins.py", line 295, in get_queryset
mop-6cdfd98d9-q8ntp mop     return get_objects_for_user(**self.get_get_objects_for_user_kwargs(qs))
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/guardian/shortcuts.py", line 515, in get_objects_for_user
mop-6cdfd98d9-q8ntp mop     new_ctype = ContentType.objects.get(app_label=app_label,
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
mop-6cdfd98d9-q8ntp mop     return getattr(self.get_queryset(), name)(*args, **kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
mop-6cdfd98d9-q8ntp mop     raise self.model.DoesNotExist(
mop-6cdfd98d9-q8ntp mop django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.
mop-6cdfd98d9-q8ntp mop 127.0.0.1 - - [01/Jul/2024:22:18:58 +0000] "GET /targets/targetgrouping/ HTTP/1.1" 500 145 "https://mop.lco.global/targetselection/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
mop-6cdfd98d9-q8ntp mop Internal Server Error: /targets/targetgrouping/
mop-6cdfd98d9-q8ntp mop Traceback (most recent call last):
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
mop-6cdfd98d9-q8ntp mop     response = get_response(request)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 199, in _get_response
mop-6cdfd98d9-q8ntp mop     response = self.process_exception_by_middleware(e, request)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
mop-6cdfd98d9-q8ntp mop     response = middleware_method(request, exception)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/tom_common/middleware.py", line 29, in process_exception
mop-6cdfd98d9-q8ntp mop     raise exception
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
mop-6cdfd98d9-q8ntp mop     response = wrapped_callback(request, *callback_args, **callback_kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
mop-6cdfd98d9-q8ntp mop     return self.dispatch(request, *args, **kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
mop-6cdfd98d9-q8ntp mop     return handler(request, *args, **kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/views/generic/list.py", line 154, in get
mop-6cdfd98d9-q8ntp mop     self.object_list = self.get_queryset()
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/guardian/mixins.py", line 295, in get_queryset
mop-6cdfd98d9-q8ntp mop     return get_objects_for_user(**self.get_get_objects_for_user_kwargs(qs))
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/guardian/shortcuts.py", line 515, in get_objects_for_user
mop-6cdfd98d9-q8ntp mop     new_ctype = ContentType.objects.get(app_label=app_label,
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
mop-6cdfd98d9-q8ntp mop     return getattr(self.get_queryset(), name)(*args, **kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
mop-6cdfd98d9-q8ntp mop     raise self.model.DoesNotExist(
mop-6cdfd98d9-q8ntp mop django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.
mop-6cdfd98d9-q8ntp mop 127.0.0.1 - - [01/Jul/2024:22:19:31 +0000] "GET /targets/targetgrouping/ HTTP/1.1" 500 145 "https://mop.lco.global/targets/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
mop-6cdfd98d9-q8ntp mop Internal Server Error: /targets/targetgrouping/
mop-6cdfd98d9-q8ntp mop Traceback (most recent call last):
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
mop-6cdfd98d9-q8ntp mop     response = get_response(request)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 199, in _get_response
mop-6cdfd98d9-q8ntp mop     response = self.process_exception_by_middleware(e, request)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
mop-6cdfd98d9-q8ntp mop     response = middleware_method(request, exception)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/tom_common/middleware.py", line 29, in process_exception
mop-6cdfd98d9-q8ntp mop     raise exception
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
mop-6cdfd98d9-q8ntp mop     response = wrapped_callback(request, *callback_args, **callback_kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
mop-6cdfd98d9-q8ntp mop     return self.dispatch(request, *args, **kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
mop-6cdfd98d9-q8ntp mop     return handler(request, *args, **kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/views/generic/list.py", line 154, in get
mop-6cdfd98d9-q8ntp mop     self.object_list = self.get_queryset()
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/guardian/mixins.py", line 295, in get_queryset
mop-6cdfd98d9-q8ntp mop     return get_objects_for_user(**self.get_get_objects_for_user_kwargs(qs))
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/guardian/shortcuts.py", line 515, in get_objects_for_user
mop-6cdfd98d9-q8ntp mop     new_ctype = ContentType.objects.get(app_label=app_label,
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
mop-6cdfd98d9-q8ntp mop     return getattr(self.get_queryset(), name)(*args, **kwargs)
mop-6cdfd98d9-q8ntp mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
mop-6cdfd98d9-q8ntp mop     raise self.model.DoesNotExist(
mop-6cdfd98d9-q8ntp mop django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.
mop-6cdfd98d9-q8ntp nginx 10.100.18.249 - - [01/Jul/2024:22:19:49 +0000] "GET /targets/targetgrouping/ HTTP/1.1" 500 145 "https://mop.lco.global/targets/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "185.193.156.145"
mop-6cdfd98d9-q8ntp mop 127.0.0.1 - - [01/Jul/2024:22:19:49 +0000] "GET /targets/targetgrouping/ HTTP/1.1" 500 145 "https://mop.lco.global/targets/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

```

**Comment by rachel3834** [comment]
@jchate6 Katarzyna just noticed that the TargetGroupingView in MOP has stopped functioning.  I've confirmed that I get the same error on my local test install too, but this worked prior to the recent MOP upgrades.  I don't think that this is an area of the code that we have customized, and I think this looks like an issue with permissions.  Can you offer any insights?

**Comment by rachel3834** [comment]
This issue has been resolved with the new Toolkit release.
