### ISSUE TITLE
Update harvest moa command

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#180]
By default the harvest MOA command is set only to update for 2023 data; update to current year. 

Also currently crashes with the error:

Target post save hook: MOA-2023-BLG-002 created: False
MOA-2023-BLG-002 Ingest done!
Traceback (most recent call last):
  File "/mop/./manage.py", line 21, in <module>
    main()
  File "/mop/./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/mop/mop/management/commands/harvest_moa.py", line 24, in handle
    Moa.find_and_ingest_photometry(list_of_targets)
  File "/mop/mop/brokers/moa.py", line 108, in find_and_ingest_photometry
    year = target.name.split('-')[1]
IndexError: list index out of range

**Comment by rachel3834** [comment]
This error was the unindended fallout from the recent change in the handling of target matching.  This means that when new MOA events are ingested, they are first crossmatched by position against the existing database, and in many cases matches are found with OGLE and in some cases Gaia events.    The MOA name is now being assigned as an alias rather than the target's primary name.  

This error wasn't encounted when the primary name of the target was an OGLE one because they take the same form as the MOA ones, but Gaia names caused a crash.  

To fix this, I've revamped the ingest function so that we loop properly over multiple years as specified in the commandline arguments, rather than attempt to infer this information from the name.
