### ISSUE TITLE
Pipeline->MOP lightcurve upload failing

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#35]
Uploads of lightcurve from the pyDANDIA pipeline to MOP are failing with the enigmatic error:
`There was a problem processing your file: Gaia23aiy/none/star_32099_Gaia23aiy_ip_auto.csv`

The fileformat for the lightcurve hasn't changed.  MOP uses a custom data processor function designed to store data in the AWS Cloud, so I wonder if there has been a change of credentials.

**Comment by rachel3834** [comment]
From Jashandeep:

Internal Server Error: /dataproducts/data/upload/                                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                                                            
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner                                                                                                                                         
    response = get_response(request)                                                                                   
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 199, in _get_response                                                                                                                                     
    response = self.process_exception_by_middleware(e, request)                              
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware                                                                                                                   
    response = middleware_method(request, exception)                                                                                                                                                                                          
  File "/usr/local/lib/python3.10/site-packages/tom_common/middleware.py", line 29, in process_exception                                                                                                                                      
    raise exception                                                                                                                                                                                                                           
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response                                                                                                                                     
    response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                                                                                                                                   
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view                                                                                                                                              
    return self.dispatch(request, *args, **kwargs)                                                                                                                                                                                            
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)                                                                  
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)                                                                           
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 144, in get                                                                                                                                               
    return self.render_to_response(self.get_context_data())                                                                                                                                                                                   
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 200, in render_to_response         
    template=self.get_template_names(),                                                                                                                                                                                                       
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 212, in get_template_names                                                                                                                                
    raise ImproperlyConfigured(                                                                                        
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'

**Comment by rachel3834** [comment]
Traced this error to a change in the TOM's photometry tom_dataproducts/data_processor.py, where the run_data_processor function had updated the expected format for the list of tuples it should receive from the processor.  MOP uses a custom data processor in order to store data in the AWS Cloud, so I have updated this to provide the correct format.
