### ISSUE TITLE
OGLE harvester for specific event

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#50]
OGLE harvester fails when run for a specific event, if that event is already known to MOP:

Starting run of OGLE event harvester
OGLE harvester: Fetching event model parameters for years ['2023']
OGLE harvester: retrieving parameters for events from 2023 with status 200
OGLE harvester: found 1256 event(s)
OGLE harvester: ingesting events
OGLE harvester: event OGLE-2023-BLG-0061 already known to MOP
Traceback (most recent call last):
  File "/mop/./manage.py", line 21, in <module>
    main()
  File "/mop/./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/mop/mop/management/commands/harvest_ogle.py", line 20, in handle
    list_of_targets = Ogle.fetch_alerts(years=[options['years']], events=options['events'])
  File "/mop/mop/brokers/ogle.py", line 56, in fetch_alerts
    list_of_targets = self.ingest_events(event_selection)
  File "/mop/mop/brokers/ogle.py", line 104, in ingest_events
    list_of_targets.append(target)
UnboundLocalError: local variable 'target' referenced before assignment

**Comment by rachel3834** [comment]
Testing on the dev and prod deployments of MOP, I was only able to repeat this issue on prod, which implies that the occurrence of the error depends on the data ingested into the instance of the DB.  A previously-crashed ingest for example could have partially ingested the data for this event in particular.  

To make the harvester process more robust, I've modified it to actively search MOP for any pre-existing instance of a target with the given name.  It will create a new target if no existing target is found, or update the existing one explicitly if it exists.
