### ISSUE TITLE
Astroquery temp files exceeding filespace

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#87]
Running eval_events_interferometry for all targets runs smoothly until it crashes with the following error:

INTERFERO: Evaluation for interferometry for Gaia23bye: Dual Field Wide guide=1
Target post save hook: Gaia23bye created: False
INTERFERO: Stored neighbouring star data in MOP
INTERFERO: Querying GSC catalog around event Gaia23bye
Traceback (most recent call last):
  File "/mop/./manage.py", line 21, in <module>
    main()
  File "/mop/./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/mop/mop/management/commands/eval_events_interferometry.py", line 33, in handle
    interferometry_prediction.evaluate_target_for_interferometry(target)
  File "/mop/mop/toolbox/interferometry_prediction.py", line 355, in evaluate_target_for_interferometry
    (gsc_table, AOFT_table) = search_gsc_catalog(target)
  File "/mop/mop/toolbox/interferometry_prediction.py", line 274, in search_gsc_catalog
    gsc_table = gsc.query_gsc(target)
  File "/mop/mop/brokers/gsc.py", line 22, in query_gsc
    result = vizier_utils.query_vizier(target, 'I/353', column_list, radius=radius, row_limit=row_limit)
  File "/mop/mop/brokers/vizier_utils.py", line 23, in query_vizier
    result = v.query_region(coord, radius=radius, catalog=catalog)
  File "/usr/local/lib/python3.10/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/astroquery/utils/process_asyncs.py", line 26, in newmethod
    response = getattr(self, async_method_name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/astroquery/vizier/core.py", line 473, in query_region_async
    response = self._request(
  File "/usr/local/lib/python3.10/site-packages/astroquery/query.py", line 324, in _request
    to_cache(response, query.request_file(self.cache_location))
  File "/usr/local/lib/python3.10/site-packages/astroquery/query.py", line 35, in to_cache
    pickle.dump(response, f)
OSError: [Errno 28] No space left on device

**Comment by rachel3834** [comment]
This appears to be due to astroquery's cache function, which persists between sessions.  
This may be configurable as follows:
> Vizier.cache_location = None
Tests indicate that the queries proceed normally

**Comment by rachel3834** [comment]
Configuring the cache this way appears to have resolved this issue.  @KKruszynska please apply this setting to any astroquerys you are running for the gaia_classifier.
