### ISSUE TITLE
AWS Upload error

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#98]

**Comment by rachel3834** [comment]
Yiannis encounters the following error when trying to upload a lightcurve file in csv format to a local instance of MOP:

> An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
> Request Method:POSTRequest URL:http://127.0.0.1:8000/dataproducts/data/upload/Django Version:4.2.3Exception > Type:ClientErrorException Value:An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

**Comment by rachel3834** [comment]
@ytsapras Please can you post the full stack trace for this error to this thread?  In particular, do you see any messages from the django-storage module?

**Comment by ytsapras** [comment]
Hi, thanks for looking into this. Here is the full error response:
```
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
Request Method: | POST
-- | --
http://127.0.0.1:8000/dataproducts/data/upload/
4.2.3
ClientError
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/botocore/client.py, line 676, in _make_api_call
tom_dataproducts.views.DataProductUploadView
/home/ytsapras/Installed_Programs/anaconda3/envs/mop/bin/python
3.10.0
['/home/ytsapras/Installed_Programs/mop',  '/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python310.zip',  '/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10',  '/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/lib-dynload',  '/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages']

```

Traceback:
```

Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/dataproducts/data/upload/

Django Version: 4.2.3
Python Version: 3.10.0
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_extensions',
 'guardian',
 'tom_common',
 'django_comments',
 'bootstrap4',
 'crispy_bootstrap4',
 'crispy_forms',
 'django_filters',
 'django_gravatar',
 'rest_framework',
 'rest_framework.authtoken',
 'tom_targets',
 'tom_alerts',
 'tom_catalogs',
 'tom_observations',
 'tom_dataproducts',
 'mop']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'tom_common.middleware.ExternalServiceMiddleware']



Traceback (most recent call last):
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/core/handlers/base.py", line 199, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/tom_common/middleware.py", line 29, in process_exception
    raise exception
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/tom_dataproducts/views.py", line 126, in form_valid
    dp.save()
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/tom_dataproducts/models.py", line 201, in save
    return super().save()
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/db/models/fields/files.py", line 93, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/core/files/storage/base.py", line 38, in save
    name = self._save(name, content)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/storages/backends/s3boto3.py", line 447, in _save
    obj.upload_fileobj(content, ExtraArgs=params)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/boto3/s3/inject.py", line 619, in object_upload_fileobj
    return self.meta.client.upload_fileobj(
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)

Exception Type: ClientError at /dataproducts/data/upload/
Exception Value: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by rachel3834** [comment]
@ytsapras Please can you try:
> python manage.py collectstatic 
and post any output to this thread?

**Comment by ytsapras** [comment]
```
(mop) $ python manage.py collectstatic
reading settings from local_settings.py
DATABASES: {'default': {'ENGINE': 'django.db.backends.postgresql', 'NAME': 'mop', 'USER': 'postgres', 'PASSWORD': 'postgres', 'HOST': '127.0.0.1', 'PORT': '5432'}}

You have requested to collect static files at the destination
location as specified in your settings.

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/home/ytsapras/Installed_Programs/mop/manage.py", line 21, in <module>
    main()
  File "/home/ytsapras/Installed_Programs/mop/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
    handler(path, prefixed_path, storage)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 368, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 322, in delete_file
    self.storage.delete(prefixed_path)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/storages/backends/s3boto3.py", line 452, in delete
    self.bucket.Object(name).delete()
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ytsapras/Installed_Programs/anaconda3/envs/mop/lib/python3.10/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
**botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied**
```
